[project]
name = "broadworks-soap-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "attr>=0.3.2",
    "broadworks-ocip>=2.2.0",
    "requests>=2.32.3",
    "zeep>=4.3.1",
]
